const menu=document.getElementById("menu"),overlay=document.getElementById("overlay"),pages=document.querySelectorAll(".page"),menuItems=document.querySelectorAll(".menu-item"),statusEl=document.getElementById("status"),countdown=document.getElementById("countdown"),countdownLabel=document.getElementById("countdownLabel"),countEl=document.getElementById("count"),listEl=document.getElementById("registrationList"),registerBtn=document.getElementById("registerBtn"),message=document.getElementById("message"),nameInput=document.getElementById("name"),studentIdInput=document.getElementById("studentId"),startText=document.getElementById("startText");
document.getElementById("maxText").textContent=MAX_PEOPLE;
const startTime=new Date(START_TIME_STRING).getTime();
startText.textContent=new Date(startTime).toLocaleString("vi-VN");
function openMenu(){menu.classList.add("open");overlay.classList.add("show")}
function closeMenu(){menu.classList.remove("open");overlay.classList.remove("show")}
function showPage(id){pages.forEach(p=>p.classList.toggle("active",p.id===id));menuItems.forEach(i=>i.classList.toggle("active",i.dataset.page===id));closeMenu();window.scrollTo({top:0,behavior:"smooth"});if(id==="activity")sync()}
document.getElementById("menuBtn").onclick=openMenu;
document.getElementById("menuClose").onclick=closeMenu;
overlay.onclick=closeMenu;
menuItems.forEach(i=>i.onclick=()=>showPage(i.dataset.page));
document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>showPage(b.dataset.go));
function setMessage(text,type){message.textContent=text;message.className="message show "+type}
function updateStatus(count){countEl.textContent=count;if(count>=MAX_PEOPLE){statusEl.textContent="● ĐÃ ĐỦ SỐ LƯỢNG";statusEl.className="status closed";registerBtn.disabled=true;countdownLabel.textContent="HOẠT ĐỘNG ĐÃ ĐỦ NGƯỜI";countdown.textContent="ĐÃ ĐỦ";return}if(Date.now()<startTime){statusEl.textContent="● CHƯA MỞ ĐĂNG KÝ";statusEl.className="status waiting";registerBtn.disabled=true}else{statusEl.textContent="● ĐANG MỞ ĐĂNG KÝ";statusEl.className="status";registerBtn.disabled=false}}
function updateCountdown(){const diff=startTime-Date.now();if(diff<=0){countdownLabel.textContent="ĐĂNG KÝ ĐANG MỞ";countdown.textContent="00:00:00";if(Number(countEl.textContent)<MAX_PEOPLE){statusEl.textContent="● ĐANG MỞ ĐĂNG KÝ";statusEl.className="status";registerBtn.disabled=false}return}const s=Math.floor(diff/1000),h=Math.floor(s/3600),m=Math.floor(s%3600/60),sec=s%60;countdownLabel.textContent="ĐĂNG KÝ SẼ MỞ SAU";countdown.textContent=[h,m,sec].map(v=>String(v).padStart(2,"0")).join(":");registerBtn.disabled=true}
setInterval(updateCountdown,1000);updateCountdown();
async function sync(){try{const res=await fetch(SCRIPT_URL+"?event="+encodeURIComponent(EVENT_ID)+"&t="+Date.now());if(!res.ok)throw new Error();const data=await res.json(),list=data.registrations||[],count=data.count||list.length;countEl.textContent=count;updateStatus(count);listEl.innerHTML="";if(!list.length){listEl.innerHTML='<tr><td colspan="4" class="empty">Chưa có người đăng ký.</td></tr>';return}list.forEach((r,i)=>{const tr=document.createElement("tr");tr.innerHTML="<td>"+(i+1)+"</td><td>"+escapeHtml(r.name)+"</td><td>"+escapeHtml(r.studentId)+"</td><td>"+escapeHtml(r.time||"")+"</td>";listEl.appendChild(tr)})}catch(e){listEl.innerHTML='<tr><td colspan="4" class="empty">Không thể tải danh sách. Vui lòng thử lại.</td></tr>'}}
function escapeHtml(v){return String(v).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]))}
registerBtn.onclick=async()=>{const name=nameInput.value.trim(),studentId=studentIdInput.value.trim();if(!name){setMessage("Vui lòng nhập họ và tên.","error");nameInput.focus();return}if(!studentId){setMessage("Vui lòng nhập mã số sinh viên.","error");studentIdInput.focus();return}if(Date.now()<startTime){setMessage("Chưa đến thời gian mở đăng ký.","error");return}if(Number(countEl.textContent)>=MAX_PEOPLE){setMessage("Hoạt động đã đủ số lượng.","error");return}registerBtn.disabled=true;registerBtn.textContent="ĐANG GỬI...";setMessage("Đang xử lý đăng ký...","success");const fd=new FormData();fd.append("event",EVENT_ID);fd.append("name",name);fd.append("studentId",studentId);fd.append("time",new Date().toLocaleString("vi-VN"));fd.append("maxLimit",MAX_PEOPLE);try{const res=await fetch(SCRIPT_URL,{method:"POST",body:fd}),data=await res.json();if(data.status==="success"){setMessage("Đăng ký thành công!","success");nameInput.value="";studentIdInput.value="";await sync()}else if(data.status==="duplicate"){setMessage("MSSV này đã đăng ký hoạt động này trước đó.","error");await sync()}else if(data.status==="full"){setMessage("Hoạt động đã đủ số lượng.","error");await sync()}else setMessage(data.message||"Không thể đăng ký. Vui lòng thử lại.","error")}catch(e){setMessage("Không thể kết nối hệ thống. Vui lòng thử lại.","error")}finally{registerBtn.textContent="ĐĂNG KÝ THAM GIA";if(Number(countEl.textContent)<MAX_PEOPLE&&Date.now()>=startTime)registerBtn.disabled=false}};
sync();
